# Site settings
baseweb: "" # the subpath of your site, e.g. /blog
web: "" # the base hostname & protocol for your site
collections:
  work:
    output: true
  events:
    output: true
defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
      header-text: white
      weight: 5
  - scope:
      path: ""
      type: events
    values:
      layout: work
      header-text: white
      weight: 5

# Build settings
markdown: kramdown
plugins:
   - jemoji
   - jekyll-redirect-from

# Metadata
keywords: "web developer, love, match, help, dating"

# Third party services
# google-fonts: "Source+Sans+Pro:400,700,900"
# google-fonts-subsets: "latin"

typekit: "xmd5huf"

# Commonly used lingo
title: "Indians on Tinder ❤️"
location: "India"
email: contact@example.com
description: > # this means to ignore newlines until the next colon
  Hey there! Need help in dating.
instagram: indiansondating
github: indiansontinder
facebook: IndiansOnDating

# Offline debug flag
dev: false
